### ISSUE TITLE
Belgium (flemish region) doesn't seem to use trains

### ISSUE THREAD

**Issue by uncentral** [mapnificent/mapnificent#6]
in half an hour you can easily reach antwerp (from brussels).

the train trainsport information has recently been added to google. 

could this be implemented?

**Comment by stefanw** [comment]
Do you have a link to the published data?

**Comment by uncentral** [comment]
Couldntbfind it at first, but here it is. Nmbs is the trains one

http://gtfs.irail.be/

**Comment by ThomasCollignon** [comment]
Hello.

It would be great to add the STIB/MIVB data: http://www.gtfs-data-exchange.com/agency/stib/
As well as the SNCB/NMBS data: http://www.gtfs-data-exchange.com/meta/5295480229593088

Is it possible?

Thanks.

**Comment by stefanw** [comment]
I renamed `flemish-region` to `flanders`.

You can check again here:
http://www.mapnificent.net/flanders/

Here is the meta data file:
https://github.com/mapnificent/mapnificent_cities/blob/master/flanders/flanders.md

I'm using all GTFS feeds listed here:
http://transitfeeds.com/l/385-flanders-belgium

Please reopen at the [Mapnificent Cities](https://github.com/mapnificent/mapnificent_cities) repo, if necessary.

**Comment by wvbesien** [comment]
There are new public datasets available. It would be very interesting if they could be implemented.

There is the datasets for mivb/stib: tram/bus/metro in Brussels:
https://data.gov.be/en/dataset/1bdd4128-9e3e-4b55-9ce1-cf2e4bd62c8a

And there is one for nmbs/sncb, the trains in Belgium:
http://www.belgianrail.be/en/customer-service/information-services-and-travel-tools/public-data.aspx

For your info: Flanders is part of Belgium, and Brussels, the capital city is geographically situated in Flanders. So to cover Flanders completely it is important to add these two. If you add the busses and trams in Wallonia, Belgium would be covered completely:
TEC (bus/tram/metro in Wallonia)
https://opendata.digitalwallonia.be/dataset/donnees-tec
If you add TEC, you can rename to Belgium.

**Comment by stefanw** [comment]
@wvbesien I already closed Flanders and created Mapnificent Belgium based on the datasets linked at Transitfeeds: http://transitfeeds.com/l/382-belgium

Are we missing any now?

**Comment by wvbesien** [comment]
Hello Stefan,

Looks good, you aren't missing any!

Willem

**Comment by uncentral** [comment]
The nmbs /sncb one doesn't seem to be taken into account.

if I take mechelen for example, there is a train of 15' to antwerp berchem. But this doesn't even show at 60' mark

**Comment by wvbesien** [comment]
@stefanw When can we expect these changes to go online?

**Comment by stefanw** [comment]
I'm using the four providers listed here: http://transitfeeds.com/l/382-belgium
The data was updated a couple of days ago. I haven't gotten a clear answer what is missing and where I can get the data to add it.

**Comment by uncentral** [comment]
the train from societe-nationale-des-chemins-de-fer-belges do not seem to
be used

**Comment by stefanw** [comment]
So it turns out that transitland lists a scraped or old version of NMBS-SNCB coming from irail here: http://transitfeeds.com/p/societe-nationale-des-chemins-de-fer-belges/528

The data is not valid for 2018 and the GTFS calendar.txt is empty.

In order to get current data, you have to apply for it here and sign something:
http://www.belgianrail.be/en/customer-service/information-services-and-travel-tools/public-data.aspx

I'm very much against special licenses (they explain their [reasons for why they think a special license is necessary on this page](http://www.belgianrail.be/en/customer-service/FAQ/public-data.aspx)). It very much seems, if the data was easily available, we wouldn't have this problem right now (which is quite ironic given one of their reasons is reliability).

I think I already tried that once to apply, never got an email back from them. Just tried it again. Please feel free to also try.

**Comment by stefanw** [comment]
I got a license form (received a mail into junk folder a couple of days after first contact). I signed it as an individual (they asked for company info) and I am waiting now. They said that they would send out GTFS exports later this week.

**Comment by stefanw** [comment]
I'm quite annoyed about the "Open Data" GTFS situation in Belgium.

- [STIB data has a license](https://opendata.stib-mivb.be/store/license) that requires showing their logo, but then has a section stating "The Producer does not wish to see its name and/or logo associated with the following elements" with a long list of topics. This is unacceptable. Currently the data is procured via irail.be (@irail)
- [De Lijn](https://www.delijn.be/en/zakelijk-aanbod/reisinfodata/gebruik-onze-data.html) also requires a separate license, but iRail seems to have that data as well, so I will not bother.
- [Wallonia/TEC data](https://opendata.digitalwallonia.be/dataset/donnees-tec/resource/0cd77130-2b03-491c-ab36-8cdef89b015d) can be downloaded easily and is under CC By 👍 
- [SNCB](http://www.belgianrail.be/en/customer-service/FAQ/public-data.aspx) is not updated on iRail, but I signed the license agreement which is not as bad as STIB's, but still quite annoying. I got access to the data now.

Transitfeeds.com only links to iRail data by default, that's why SNCB data was not up-to-date.

New version available as usual: https://www.mapnificent.net/belgium/
